// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface CommitmentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.CommitmentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes commitments = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getCommitmentsList();
  /**
   * <code>repeated bytes commitments = 1;</code>
   */
  int getCommitmentsCount();
  /**
   * <code>repeated bytes commitments = 1;</code>
   */
  com.google.protobuf.ByteString getCommitments(int index);
}
