// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes adsIds = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getAdsIdsList();
  /**
   * <code>repeated bytes adsIds = 1;</code>
   */
  int getAdsIdsCount();
  /**
   * <code>repeated bytes adsIds = 1;</code>
   */
  com.google.protobuf.ByteString getAdsIds(int index);

  /**
   * <code>int32 commitmentNumber = 2;</code>
   */
  int getCommitmentNumber();
}
