// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes adsId = 1;</code>
   */
  com.google.protobuf.ByteString getAdsId();

  /**
   * <code>int32 commitmentNumber = 2;</code>
   */
  int getCommitmentNumber();
}
