// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  java.util.List<io.grpc.bverify.Receipt> 
      getReceiptsList();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  io.grpc.bverify.Receipt getReceipts(int index);
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  int getReceiptsCount();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  java.util.List<? extends io.grpc.bverify.ReceiptOrBuilder> 
      getReceiptsOrBuilderList();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  io.grpc.bverify.ReceiptOrBuilder getReceiptsOrBuilder(
      int index);

  /**
   * <code>int32 commitmentNumber = 2;</code>
   */
  int getCommitmentNumber();

  /**
   * <code>bytes commitment = 3;</code>
   */
  com.google.protobuf.ByteString getCommitment();
}
