// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

/**
 * Protobuf type {@code api.DataResponse}
 */
public  final class DataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.DataResponse)
    DataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataResponse.newBuilder() to construct.
  private DataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataResponse() {
    receipts_ = java.util.Collections.emptyList();
    commitmentNumber_ = 0;
    commitment_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              receipts_ = new java.util.ArrayList<io.grpc.bverify.Receipt>();
              mutable_bitField0_ |= 0x00000001;
            }
            receipts_.add(
                input.readMessage(io.grpc.bverify.Receipt.parser(), extensionRegistry));
            break;
          }
          case 16: {

            commitmentNumber_ = input.readInt32();
            break;
          }
          case 26: {

            commitment_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        receipts_ = java.util.Collections.unmodifiableList(receipts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.bverify.Api.internal_static_api_DataResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.bverify.Api.internal_static_api_DataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.bverify.DataResponse.class, io.grpc.bverify.DataResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RECEIPTS_FIELD_NUMBER = 1;
  private java.util.List<io.grpc.bverify.Receipt> receipts_;
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  public java.util.List<io.grpc.bverify.Receipt> getReceiptsList() {
    return receipts_;
  }
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  public java.util.List<? extends io.grpc.bverify.ReceiptOrBuilder> 
      getReceiptsOrBuilderList() {
    return receipts_;
  }
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  public int getReceiptsCount() {
    return receipts_.size();
  }
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  public io.grpc.bverify.Receipt getReceipts(int index) {
    return receipts_.get(index);
  }
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  public io.grpc.bverify.ReceiptOrBuilder getReceiptsOrBuilder(
      int index) {
    return receipts_.get(index);
  }

  public static final int COMMITMENTNUMBER_FIELD_NUMBER = 2;
  private int commitmentNumber_;
  /**
   * <code>int32 commitmentNumber = 2;</code>
   */
  public int getCommitmentNumber() {
    return commitmentNumber_;
  }

  public static final int COMMITMENT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString commitment_;
  /**
   * <code>bytes commitment = 3;</code>
   */
  public com.google.protobuf.ByteString getCommitment() {
    return commitment_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < receipts_.size(); i++) {
      output.writeMessage(1, receipts_.get(i));
    }
    if (commitmentNumber_ != 0) {
      output.writeInt32(2, commitmentNumber_);
    }
    if (!commitment_.isEmpty()) {
      output.writeBytes(3, commitment_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < receipts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, receipts_.get(i));
    }
    if (commitmentNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, commitmentNumber_);
    }
    if (!commitment_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, commitment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.bverify.DataResponse)) {
      return super.equals(obj);
    }
    io.grpc.bverify.DataResponse other = (io.grpc.bverify.DataResponse) obj;

    boolean result = true;
    result = result && getReceiptsList()
        .equals(other.getReceiptsList());
    result = result && (getCommitmentNumber()
        == other.getCommitmentNumber());
    result = result && getCommitment()
        .equals(other.getCommitment());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReceiptsCount() > 0) {
      hash = (37 * hash) + RECEIPTS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiptsList().hashCode();
    }
    hash = (37 * hash) + COMMITMENTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCommitmentNumber();
    hash = (37 * hash) + COMMITMENT_FIELD_NUMBER;
    hash = (53 * hash) + getCommitment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.bverify.DataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.DataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.DataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.DataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.DataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.bverify.DataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.DataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.DataResponse)
      io.grpc.bverify.DataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.bverify.Api.internal_static_api_DataResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.bverify.Api.internal_static_api_DataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.bverify.DataResponse.class, io.grpc.bverify.DataResponse.Builder.class);
    }

    // Construct using io.grpc.bverify.DataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReceiptsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (receiptsBuilder_ == null) {
        receipts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        receiptsBuilder_.clear();
      }
      commitmentNumber_ = 0;

      commitment_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.bverify.Api.internal_static_api_DataResponse_descriptor;
    }

    public io.grpc.bverify.DataResponse getDefaultInstanceForType() {
      return io.grpc.bverify.DataResponse.getDefaultInstance();
    }

    public io.grpc.bverify.DataResponse build() {
      io.grpc.bverify.DataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.bverify.DataResponse buildPartial() {
      io.grpc.bverify.DataResponse result = new io.grpc.bverify.DataResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (receiptsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          receipts_ = java.util.Collections.unmodifiableList(receipts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.receipts_ = receipts_;
      } else {
        result.receipts_ = receiptsBuilder_.build();
      }
      result.commitmentNumber_ = commitmentNumber_;
      result.commitment_ = commitment_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.bverify.DataResponse) {
        return mergeFrom((io.grpc.bverify.DataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.bverify.DataResponse other) {
      if (other == io.grpc.bverify.DataResponse.getDefaultInstance()) return this;
      if (receiptsBuilder_ == null) {
        if (!other.receipts_.isEmpty()) {
          if (receipts_.isEmpty()) {
            receipts_ = other.receipts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReceiptsIsMutable();
            receipts_.addAll(other.receipts_);
          }
          onChanged();
        }
      } else {
        if (!other.receipts_.isEmpty()) {
          if (receiptsBuilder_.isEmpty()) {
            receiptsBuilder_.dispose();
            receiptsBuilder_ = null;
            receipts_ = other.receipts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            receiptsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReceiptsFieldBuilder() : null;
          } else {
            receiptsBuilder_.addAllMessages(other.receipts_);
          }
        }
      }
      if (other.getCommitmentNumber() != 0) {
        setCommitmentNumber(other.getCommitmentNumber());
      }
      if (other.getCommitment() != com.google.protobuf.ByteString.EMPTY) {
        setCommitment(other.getCommitment());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.bverify.DataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.bverify.DataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.grpc.bverify.Receipt> receipts_ =
      java.util.Collections.emptyList();
    private void ensureReceiptsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        receipts_ = new java.util.ArrayList<io.grpc.bverify.Receipt>(receipts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder> receiptsBuilder_;

    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public java.util.List<io.grpc.bverify.Receipt> getReceiptsList() {
      if (receiptsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(receipts_);
      } else {
        return receiptsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public int getReceiptsCount() {
      if (receiptsBuilder_ == null) {
        return receipts_.size();
      } else {
        return receiptsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public io.grpc.bverify.Receipt getReceipts(int index) {
      if (receiptsBuilder_ == null) {
        return receipts_.get(index);
      } else {
        return receiptsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder setReceipts(
        int index, io.grpc.bverify.Receipt value) {
      if (receiptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReceiptsIsMutable();
        receipts_.set(index, value);
        onChanged();
      } else {
        receiptsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder setReceipts(
        int index, io.grpc.bverify.Receipt.Builder builderForValue) {
      if (receiptsBuilder_ == null) {
        ensureReceiptsIsMutable();
        receipts_.set(index, builderForValue.build());
        onChanged();
      } else {
        receiptsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder addReceipts(io.grpc.bverify.Receipt value) {
      if (receiptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReceiptsIsMutable();
        receipts_.add(value);
        onChanged();
      } else {
        receiptsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder addReceipts(
        int index, io.grpc.bverify.Receipt value) {
      if (receiptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReceiptsIsMutable();
        receipts_.add(index, value);
        onChanged();
      } else {
        receiptsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder addReceipts(
        io.grpc.bverify.Receipt.Builder builderForValue) {
      if (receiptsBuilder_ == null) {
        ensureReceiptsIsMutable();
        receipts_.add(builderForValue.build());
        onChanged();
      } else {
        receiptsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder addReceipts(
        int index, io.grpc.bverify.Receipt.Builder builderForValue) {
      if (receiptsBuilder_ == null) {
        ensureReceiptsIsMutable();
        receipts_.add(index, builderForValue.build());
        onChanged();
      } else {
        receiptsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder addAllReceipts(
        java.lang.Iterable<? extends io.grpc.bverify.Receipt> values) {
      if (receiptsBuilder_ == null) {
        ensureReceiptsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, receipts_);
        onChanged();
      } else {
        receiptsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder clearReceipts() {
      if (receiptsBuilder_ == null) {
        receipts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        receiptsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public Builder removeReceipts(int index) {
      if (receiptsBuilder_ == null) {
        ensureReceiptsIsMutable();
        receipts_.remove(index);
        onChanged();
      } else {
        receiptsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public io.grpc.bverify.Receipt.Builder getReceiptsBuilder(
        int index) {
      return getReceiptsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public io.grpc.bverify.ReceiptOrBuilder getReceiptsOrBuilder(
        int index) {
      if (receiptsBuilder_ == null) {
        return receipts_.get(index);  } else {
        return receiptsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public java.util.List<? extends io.grpc.bverify.ReceiptOrBuilder> 
         getReceiptsOrBuilderList() {
      if (receiptsBuilder_ != null) {
        return receiptsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(receipts_);
      }
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public io.grpc.bverify.Receipt.Builder addReceiptsBuilder() {
      return getReceiptsFieldBuilder().addBuilder(
          io.grpc.bverify.Receipt.getDefaultInstance());
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public io.grpc.bverify.Receipt.Builder addReceiptsBuilder(
        int index) {
      return getReceiptsFieldBuilder().addBuilder(
          index, io.grpc.bverify.Receipt.getDefaultInstance());
    }
    /**
     * <code>repeated .api.Receipt receipts = 1;</code>
     */
    public java.util.List<io.grpc.bverify.Receipt.Builder> 
         getReceiptsBuilderList() {
      return getReceiptsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder> 
        getReceiptsFieldBuilder() {
      if (receiptsBuilder_ == null) {
        receiptsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder>(
                receipts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        receipts_ = null;
      }
      return receiptsBuilder_;
    }

    private int commitmentNumber_ ;
    /**
     * <code>int32 commitmentNumber = 2;</code>
     */
    public int getCommitmentNumber() {
      return commitmentNumber_;
    }
    /**
     * <code>int32 commitmentNumber = 2;</code>
     */
    public Builder setCommitmentNumber(int value) {
      
      commitmentNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 commitmentNumber = 2;</code>
     */
    public Builder clearCommitmentNumber() {
      
      commitmentNumber_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString commitment_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes commitment = 3;</code>
     */
    public com.google.protobuf.ByteString getCommitment() {
      return commitment_;
    }
    /**
     * <code>bytes commitment = 3;</code>
     */
    public Builder setCommitment(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commitment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes commitment = 3;</code>
     */
    public Builder clearCommitment() {
      
      commitment_ = getDefaultInstance().getCommitment();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.DataResponse)
  }

  // @@protoc_insertion_point(class_scope:api.DataResponse)
  private static final io.grpc.bverify.DataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.bverify.DataResponse();
  }

  public static io.grpc.bverify.DataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataResponse>
      PARSER = new com.google.protobuf.AbstractParser<DataResponse>() {
    public DataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataResponse> getParserForType() {
    return PARSER;
  }

  public io.grpc.bverify.DataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

