// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface EmptyLeafOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bverify.EmptyLeaf)
    com.google.protobuf.MessageOrBuilder {
}
