// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface ForwardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ForwardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool added = 1;</code>
   */
  boolean getAdded();
}
