// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface ForwardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ForwardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequest getRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>string forward_to_id = 2;</code>
   */
  java.lang.String getForwardToId();
  /**
   * <code>string forward_to_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getForwardToIdBytes();
}
