// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface GetForwardedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.GetForwardedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequest getRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequestOrBuilder getRequestOrBuilder();
}
