// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

/**
 * <pre>
 **
 *	InteriorNode has left or right children.
 *	Omitted children are used in caching strategies:
 * 	If a child is omitted, the client can use the current 
 * 	value.
 * </pre>
 *
 * Protobuf type {@code bverify.InteriorNode}
 */
public  final class InteriorNode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bverify.InteriorNode)
    InteriorNodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InteriorNode.newBuilder() to construct.
  private InteriorNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InteriorNode() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InteriorNode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.grpc.bverify.Node.Builder subBuilder = null;
            if (left_ != null) {
              subBuilder = left_.toBuilder();
            }
            left_ = input.readMessage(io.grpc.bverify.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(left_);
              left_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.grpc.bverify.Node.Builder subBuilder = null;
            if (right_ != null) {
              subBuilder = right_.toBuilder();
            }
            right_ = input.readMessage(io.grpc.bverify.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(right_);
              right_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.bverify.BVerifyAPI.internal_static_bverify_InteriorNode_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.bverify.BVerifyAPI.internal_static_bverify_InteriorNode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.bverify.InteriorNode.class, io.grpc.bverify.InteriorNode.Builder.class);
  }

  public static final int LEFT_FIELD_NUMBER = 1;
  private io.grpc.bverify.Node left_;
  /**
   * <code>.bverify.Node left = 1;</code>
   */
  public boolean hasLeft() {
    return left_ != null;
  }
  /**
   * <code>.bverify.Node left = 1;</code>
   */
  public io.grpc.bverify.Node getLeft() {
    return left_ == null ? io.grpc.bverify.Node.getDefaultInstance() : left_;
  }
  /**
   * <code>.bverify.Node left = 1;</code>
   */
  public io.grpc.bverify.NodeOrBuilder getLeftOrBuilder() {
    return getLeft();
  }

  public static final int RIGHT_FIELD_NUMBER = 2;
  private io.grpc.bverify.Node right_;
  /**
   * <code>.bverify.Node right = 2;</code>
   */
  public boolean hasRight() {
    return right_ != null;
  }
  /**
   * <code>.bverify.Node right = 2;</code>
   */
  public io.grpc.bverify.Node getRight() {
    return right_ == null ? io.grpc.bverify.Node.getDefaultInstance() : right_;
  }
  /**
   * <code>.bverify.Node right = 2;</code>
   */
  public io.grpc.bverify.NodeOrBuilder getRightOrBuilder() {
    return getRight();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (left_ != null) {
      output.writeMessage(1, getLeft());
    }
    if (right_ != null) {
      output.writeMessage(2, getRight());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (left_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeft());
    }
    if (right_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRight());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.bverify.InteriorNode)) {
      return super.equals(obj);
    }
    io.grpc.bverify.InteriorNode other = (io.grpc.bverify.InteriorNode) obj;

    boolean result = true;
    result = result && (hasLeft() == other.hasLeft());
    if (hasLeft()) {
      result = result && getLeft()
          .equals(other.getLeft());
    }
    result = result && (hasRight() == other.hasRight());
    if (hasRight()) {
      result = result && getRight()
          .equals(other.getRight());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeft()) {
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + getLeft().hashCode();
    }
    if (hasRight()) {
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getRight().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.bverify.InteriorNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.InteriorNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.InteriorNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.InteriorNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.bverify.InteriorNode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *	InteriorNode has left or right children.
   *	Omitted children are used in caching strategies:
   * 	If a child is omitted, the client can use the current 
   * 	value.
   * </pre>
   *
   * Protobuf type {@code bverify.InteriorNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bverify.InteriorNode)
      io.grpc.bverify.InteriorNodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_InteriorNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_InteriorNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.bverify.InteriorNode.class, io.grpc.bverify.InteriorNode.Builder.class);
    }

    // Construct using io.grpc.bverify.InteriorNode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (leftBuilder_ == null) {
        left_ = null;
      } else {
        left_ = null;
        leftBuilder_ = null;
      }
      if (rightBuilder_ == null) {
        right_ = null;
      } else {
        right_ = null;
        rightBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_InteriorNode_descriptor;
    }

    public io.grpc.bverify.InteriorNode getDefaultInstanceForType() {
      return io.grpc.bverify.InteriorNode.getDefaultInstance();
    }

    public io.grpc.bverify.InteriorNode build() {
      io.grpc.bverify.InteriorNode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.bverify.InteriorNode buildPartial() {
      io.grpc.bverify.InteriorNode result = new io.grpc.bverify.InteriorNode(this);
      if (leftBuilder_ == null) {
        result.left_ = left_;
      } else {
        result.left_ = leftBuilder_.build();
      }
      if (rightBuilder_ == null) {
        result.right_ = right_;
      } else {
        result.right_ = rightBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.bverify.InteriorNode) {
        return mergeFrom((io.grpc.bverify.InteriorNode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.bverify.InteriorNode other) {
      if (other == io.grpc.bverify.InteriorNode.getDefaultInstance()) return this;
      if (other.hasLeft()) {
        mergeLeft(other.getLeft());
      }
      if (other.hasRight()) {
        mergeRight(other.getRight());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.bverify.InteriorNode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.bverify.InteriorNode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.grpc.bverify.Node left_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> leftBuilder_;
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public boolean hasLeft() {
      return leftBuilder_ != null || left_ != null;
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public io.grpc.bverify.Node getLeft() {
      if (leftBuilder_ == null) {
        return left_ == null ? io.grpc.bverify.Node.getDefaultInstance() : left_;
      } else {
        return leftBuilder_.getMessage();
      }
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public Builder setLeft(io.grpc.bverify.Node value) {
      if (leftBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        left_ = value;
        onChanged();
      } else {
        leftBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public Builder setLeft(
        io.grpc.bverify.Node.Builder builderForValue) {
      if (leftBuilder_ == null) {
        left_ = builderForValue.build();
        onChanged();
      } else {
        leftBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public Builder mergeLeft(io.grpc.bverify.Node value) {
      if (leftBuilder_ == null) {
        if (left_ != null) {
          left_ =
            io.grpc.bverify.Node.newBuilder(left_).mergeFrom(value).buildPartial();
        } else {
          left_ = value;
        }
        onChanged();
      } else {
        leftBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public Builder clearLeft() {
      if (leftBuilder_ == null) {
        left_ = null;
        onChanged();
      } else {
        left_ = null;
        leftBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public io.grpc.bverify.Node.Builder getLeftBuilder() {
      
      onChanged();
      return getLeftFieldBuilder().getBuilder();
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    public io.grpc.bverify.NodeOrBuilder getLeftOrBuilder() {
      if (leftBuilder_ != null) {
        return leftBuilder_.getMessageOrBuilder();
      } else {
        return left_ == null ?
            io.grpc.bverify.Node.getDefaultInstance() : left_;
      }
    }
    /**
     * <code>.bverify.Node left = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> 
        getLeftFieldBuilder() {
      if (leftBuilder_ == null) {
        leftBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder>(
                getLeft(),
                getParentForChildren(),
                isClean());
        left_ = null;
      }
      return leftBuilder_;
    }

    private io.grpc.bverify.Node right_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> rightBuilder_;
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public boolean hasRight() {
      return rightBuilder_ != null || right_ != null;
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public io.grpc.bverify.Node getRight() {
      if (rightBuilder_ == null) {
        return right_ == null ? io.grpc.bverify.Node.getDefaultInstance() : right_;
      } else {
        return rightBuilder_.getMessage();
      }
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public Builder setRight(io.grpc.bverify.Node value) {
      if (rightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        right_ = value;
        onChanged();
      } else {
        rightBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public Builder setRight(
        io.grpc.bverify.Node.Builder builderForValue) {
      if (rightBuilder_ == null) {
        right_ = builderForValue.build();
        onChanged();
      } else {
        rightBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public Builder mergeRight(io.grpc.bverify.Node value) {
      if (rightBuilder_ == null) {
        if (right_ != null) {
          right_ =
            io.grpc.bverify.Node.newBuilder(right_).mergeFrom(value).buildPartial();
        } else {
          right_ = value;
        }
        onChanged();
      } else {
        rightBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public Builder clearRight() {
      if (rightBuilder_ == null) {
        right_ = null;
        onChanged();
      } else {
        right_ = null;
        rightBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public io.grpc.bverify.Node.Builder getRightBuilder() {
      
      onChanged();
      return getRightFieldBuilder().getBuilder();
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    public io.grpc.bverify.NodeOrBuilder getRightOrBuilder() {
      if (rightBuilder_ != null) {
        return rightBuilder_.getMessageOrBuilder();
      } else {
        return right_ == null ?
            io.grpc.bverify.Node.getDefaultInstance() : right_;
      }
    }
    /**
     * <code>.bverify.Node right = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> 
        getRightFieldBuilder() {
      if (rightBuilder_ == null) {
        rightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder>(
                getRight(),
                getParentForChildren(),
                isClean());
        right_ = null;
      }
      return rightBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bverify.InteriorNode)
  }

  // @@protoc_insertion_point(class_scope:bverify.InteriorNode)
  private static final io.grpc.bverify.InteriorNode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.bverify.InteriorNode();
  }

  public static io.grpc.bverify.InteriorNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InteriorNode>
      PARSER = new com.google.protobuf.AbstractParser<InteriorNode>() {
    public InteriorNode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InteriorNode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InteriorNode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InteriorNode> getParserForType() {
    return PARSER;
  }

  public io.grpc.bverify.InteriorNode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

