// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface InteriorNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bverify.InteriorNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bverify.Node left = 1;</code>
   */
  boolean hasLeft();
  /**
   * <code>.bverify.Node left = 1;</code>
   */
  io.grpc.bverify.Node getLeft();
  /**
   * <code>.bverify.Node left = 1;</code>
   */
  io.grpc.bverify.NodeOrBuilder getLeftOrBuilder();

  /**
   * <code>.bverify.Node right = 2;</code>
   */
  boolean hasRight();
  /**
   * <code>.bverify.Node right = 2;</code>
   */
  io.grpc.bverify.Node getRight();
  /**
   * <code>.bverify.Node right = 2;</code>
   */
  io.grpc.bverify.NodeOrBuilder getRightOrBuilder();
}
