// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface IssueReceiptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.IssueReceiptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool scheduled = 1;</code>
   */
  boolean getScheduled();
}
