// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface IssueReceiptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.IssueReceiptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string issuer_id = 1;</code>
   */
  java.lang.String getIssuerId();
  /**
   * <code>string issuer_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIssuerIdBytes();

  /**
   * <code>string recepient_id = 2;</code>
   */
  java.lang.String getRecepientId();
  /**
   * <code>string recepient_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecepientIdBytes();

  /**
   * <code>.api.Receipt receipt = 3;</code>
   */
  boolean hasReceipt();
  /**
   * <code>.api.Receipt receipt = 3;</code>
   */
  io.grpc.bverify.Receipt getReceipt();
  /**
   * <code>.api.Receipt receipt = 3;</code>
   */
  io.grpc.bverify.ReceiptOrBuilder getReceiptOrBuilder();

  /**
   * <code>.api.Signature signature = 4;</code>
   */
  boolean hasSignature();
  /**
   * <code>.api.Signature signature = 4;</code>
   */
  io.grpc.bverify.Signature getSignature();
  /**
   * <code>.api.Signature signature = 4;</code>
   */
  io.grpc.bverify.SignatureOrBuilder getSignatureOrBuilder();
}
