// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface LeafOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bverify.Leaf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();
}
