// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface MerklePrefixTrieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bverify.MerklePrefixTrie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bverify.Node root = 1;</code>
   */
  boolean hasRoot();
  /**
   * <code>.bverify.Node root = 1;</code>
   */
  io.grpc.bverify.Node getRoot();
  /**
   * <code>.bverify.Node root = 1;</code>
   */
  io.grpc.bverify.NodeOrBuilder getRootOrBuilder();
}
