// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

/**
 * <pre>
 **
 *	A full or partial MerklePrefixTrie 
 * </pre>
 *
 * Protobuf type {@code bverify.MerklePrefixTrie}
 */
public  final class MerklePrefixTrie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bverify.MerklePrefixTrie)
    MerklePrefixTrieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MerklePrefixTrie.newBuilder() to construct.
  private MerklePrefixTrie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MerklePrefixTrie() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MerklePrefixTrie(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.grpc.bverify.Node.Builder subBuilder = null;
            if (root_ != null) {
              subBuilder = root_.toBuilder();
            }
            root_ = input.readMessage(io.grpc.bverify.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(root_);
              root_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.bverify.BVerifyAPI.internal_static_bverify_MerklePrefixTrie_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.bverify.BVerifyAPI.internal_static_bverify_MerklePrefixTrie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.bverify.MerklePrefixTrie.class, io.grpc.bverify.MerklePrefixTrie.Builder.class);
  }

  public static final int ROOT_FIELD_NUMBER = 1;
  private io.grpc.bverify.Node root_;
  /**
   * <code>.bverify.Node root = 1;</code>
   */
  public boolean hasRoot() {
    return root_ != null;
  }
  /**
   * <code>.bverify.Node root = 1;</code>
   */
  public io.grpc.bverify.Node getRoot() {
    return root_ == null ? io.grpc.bverify.Node.getDefaultInstance() : root_;
  }
  /**
   * <code>.bverify.Node root = 1;</code>
   */
  public io.grpc.bverify.NodeOrBuilder getRootOrBuilder() {
    return getRoot();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (root_ != null) {
      output.writeMessage(1, getRoot());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (root_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRoot());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.bverify.MerklePrefixTrie)) {
      return super.equals(obj);
    }
    io.grpc.bverify.MerklePrefixTrie other = (io.grpc.bverify.MerklePrefixTrie) obj;

    boolean result = true;
    result = result && (hasRoot() == other.hasRoot());
    if (hasRoot()) {
      result = result && getRoot()
          .equals(other.getRoot());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRoot()) {
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRoot().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.MerklePrefixTrie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.bverify.MerklePrefixTrie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *	A full or partial MerklePrefixTrie 
   * </pre>
   *
   * Protobuf type {@code bverify.MerklePrefixTrie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bverify.MerklePrefixTrie)
      io.grpc.bverify.MerklePrefixTrieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_MerklePrefixTrie_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_MerklePrefixTrie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.bverify.MerklePrefixTrie.class, io.grpc.bverify.MerklePrefixTrie.Builder.class);
    }

    // Construct using io.grpc.bverify.MerklePrefixTrie.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (rootBuilder_ == null) {
        root_ = null;
      } else {
        root_ = null;
        rootBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.bverify.BVerifyAPI.internal_static_bverify_MerklePrefixTrie_descriptor;
    }

    public io.grpc.bverify.MerklePrefixTrie getDefaultInstanceForType() {
      return io.grpc.bverify.MerklePrefixTrie.getDefaultInstance();
    }

    public io.grpc.bverify.MerklePrefixTrie build() {
      io.grpc.bverify.MerklePrefixTrie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.bverify.MerklePrefixTrie buildPartial() {
      io.grpc.bverify.MerklePrefixTrie result = new io.grpc.bverify.MerklePrefixTrie(this);
      if (rootBuilder_ == null) {
        result.root_ = root_;
      } else {
        result.root_ = rootBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.bverify.MerklePrefixTrie) {
        return mergeFrom((io.grpc.bverify.MerklePrefixTrie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.bverify.MerklePrefixTrie other) {
      if (other == io.grpc.bverify.MerklePrefixTrie.getDefaultInstance()) return this;
      if (other.hasRoot()) {
        mergeRoot(other.getRoot());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.bverify.MerklePrefixTrie parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.bverify.MerklePrefixTrie) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.grpc.bverify.Node root_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> rootBuilder_;
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public boolean hasRoot() {
      return rootBuilder_ != null || root_ != null;
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public io.grpc.bverify.Node getRoot() {
      if (rootBuilder_ == null) {
        return root_ == null ? io.grpc.bverify.Node.getDefaultInstance() : root_;
      } else {
        return rootBuilder_.getMessage();
      }
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public Builder setRoot(io.grpc.bverify.Node value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        root_ = value;
        onChanged();
      } else {
        rootBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public Builder setRoot(
        io.grpc.bverify.Node.Builder builderForValue) {
      if (rootBuilder_ == null) {
        root_ = builderForValue.build();
        onChanged();
      } else {
        rootBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public Builder mergeRoot(io.grpc.bverify.Node value) {
      if (rootBuilder_ == null) {
        if (root_ != null) {
          root_ =
            io.grpc.bverify.Node.newBuilder(root_).mergeFrom(value).buildPartial();
        } else {
          root_ = value;
        }
        onChanged();
      } else {
        rootBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public Builder clearRoot() {
      if (rootBuilder_ == null) {
        root_ = null;
        onChanged();
      } else {
        root_ = null;
        rootBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public io.grpc.bverify.Node.Builder getRootBuilder() {
      
      onChanged();
      return getRootFieldBuilder().getBuilder();
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    public io.grpc.bverify.NodeOrBuilder getRootOrBuilder() {
      if (rootBuilder_ != null) {
        return rootBuilder_.getMessageOrBuilder();
      } else {
        return root_ == null ?
            io.grpc.bverify.Node.getDefaultInstance() : root_;
      }
    }
    /**
     * <code>.bverify.Node root = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder> 
        getRootFieldBuilder() {
      if (rootBuilder_ == null) {
        rootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.bverify.Node, io.grpc.bverify.Node.Builder, io.grpc.bverify.NodeOrBuilder>(
                getRoot(),
                getParentForChildren(),
                isClean());
        root_ = null;
      }
      return rootBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bverify.MerklePrefixTrie)
  }

  // @@protoc_insertion_point(class_scope:bverify.MerklePrefixTrie)
  private static final io.grpc.bverify.MerklePrefixTrie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.bverify.MerklePrefixTrie();
  }

  public static io.grpc.bverify.MerklePrefixTrie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MerklePrefixTrie>
      PARSER = new com.google.protobuf.AbstractParser<MerklePrefixTrie>() {
    public MerklePrefixTrie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MerklePrefixTrie(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MerklePrefixTrie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MerklePrefixTrie> getParserForType() {
    return PARSER;
  }

  public io.grpc.bverify.MerklePrefixTrie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

