// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bverify.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bverify.InteriorNode interior_node = 1;</code>
   */
  boolean hasInteriorNode();
  /**
   * <code>.bverify.InteriorNode interior_node = 1;</code>
   */
  io.grpc.bverify.InteriorNode getInteriorNode();
  /**
   * <code>.bverify.InteriorNode interior_node = 1;</code>
   */
  io.grpc.bverify.InteriorNodeOrBuilder getInteriorNodeOrBuilder();

  /**
   * <code>.bverify.Leaf leaf = 2;</code>
   */
  boolean hasLeaf();
  /**
   * <code>.bverify.Leaf leaf = 2;</code>
   */
  io.grpc.bverify.Leaf getLeaf();
  /**
   * <code>.bverify.Leaf leaf = 2;</code>
   */
  io.grpc.bverify.LeafOrBuilder getLeafOrBuilder();

  /**
   * <code>.bverify.Stub stub = 3;</code>
   */
  boolean hasStub();
  /**
   * <code>.bverify.Stub stub = 3;</code>
   */
  io.grpc.bverify.Stub getStub();
  /**
   * <code>.bverify.Stub stub = 3;</code>
   */
  io.grpc.bverify.StubOrBuilder getStubOrBuilder();

  /**
   * <code>.bverify.EmptyLeaf emptyleaf = 4;</code>
   */
  boolean hasEmptyleaf();
  /**
   * <code>.bverify.EmptyLeaf emptyleaf = 4;</code>
   */
  io.grpc.bverify.EmptyLeaf getEmptyleaf();
  /**
   * <code>.bverify.EmptyLeaf emptyleaf = 4;</code>
   */
  io.grpc.bverify.EmptyLeafOrBuilder getEmptyleafOrBuilder();

  public io.grpc.bverify.Node.NodeCase getNodeCase();
}
