// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface PathResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PathResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.serialization.generated.MerklePrefixTrie path = 1;</code>
   */
  boolean hasPath();
  /**
   * <code>.serialization.generated.MerklePrefixTrie path = 1;</code>
   */
  serialization.generated.MptSerialization.MerklePrefixTrie getPath();
  /**
   * <code>.serialization.generated.MerklePrefixTrie path = 1;</code>
   */
  serialization.generated.MptSerialization.MerklePrefixTrieOrBuilder getPathOrBuilder();
}
