// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface SignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Signature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signer_id = 1;</code>
   */
  java.lang.String getSignerId();
  /**
   * <code>string signer_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSignerIdBytes();

  /**
   * <code>bytes signature = 2;</code>
   */
  com.google.protobuf.ByteString getSignature();
}
