// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface SubmitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SubmitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   */
  boolean getAccepted();
}
