// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface SubmitSignatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SubmitSignatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequest getRequest();
  /**
   * <code>.api.IssueReceiptRequest request = 1;</code>
   */
  io.grpc.bverify.IssueReceiptRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.api.Signature signature = 2;</code>
   */
  boolean hasSignature();
  /**
   * <code>.api.Signature signature = 2;</code>
   */
  io.grpc.bverify.Signature getSignature();
  /**
   * <code>.api.Signature signature = 2;</code>
   */
  io.grpc.bverify.SignatureOrBuilder getSignatureOrBuilder();
}
