// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

/**
 * Protobuf type {@code api.TransferReceiptRequest}
 */
public  final class TransferReceiptRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.TransferReceiptRequest)
    TransferReceiptRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransferReceiptRequest.newBuilder() to construct.
  private TransferReceiptRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransferReceiptRequest() {
    currentOwnerId_ = "";
    newOwnerId_ = "";
    signatureWarehouseCurrent_ = com.google.protobuf.ByteString.EMPTY;
    signatureCurrentOwner_ = com.google.protobuf.ByteString.EMPTY;
    signatureWarehouseNew_ = com.google.protobuf.ByteString.EMPTY;
    signatureNewOwner_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransferReceiptRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.grpc.bverify.Receipt.Builder subBuilder = null;
            if (receipt_ != null) {
              subBuilder = receipt_.toBuilder();
            }
            receipt_ = input.readMessage(io.grpc.bverify.Receipt.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(receipt_);
              receipt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            currentOwnerId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            newOwnerId_ = s;
            break;
          }
          case 34: {

            signatureWarehouseCurrent_ = input.readBytes();
            break;
          }
          case 42: {

            signatureCurrentOwner_ = input.readBytes();
            break;
          }
          case 50: {

            signatureWarehouseNew_ = input.readBytes();
            break;
          }
          case 58: {

            signatureNewOwner_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.bverify.Api.internal_static_api_TransferReceiptRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.bverify.Api.internal_static_api_TransferReceiptRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.bverify.TransferReceiptRequest.class, io.grpc.bverify.TransferReceiptRequest.Builder.class);
  }

  public static final int RECEIPT_FIELD_NUMBER = 1;
  private io.grpc.bverify.Receipt receipt_;
  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  public boolean hasReceipt() {
    return receipt_ != null;
  }
  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  public io.grpc.bverify.Receipt getReceipt() {
    return receipt_ == null ? io.grpc.bverify.Receipt.getDefaultInstance() : receipt_;
  }
  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  public io.grpc.bverify.ReceiptOrBuilder getReceiptOrBuilder() {
    return getReceipt();
  }

  public static final int CURRENT_OWNER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object currentOwnerId_;
  /**
   * <code>string current_owner_id = 2;</code>
   */
  public java.lang.String getCurrentOwnerId() {
    java.lang.Object ref = currentOwnerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentOwnerId_ = s;
      return s;
    }
  }
  /**
   * <code>string current_owner_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentOwnerIdBytes() {
    java.lang.Object ref = currentOwnerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentOwnerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEW_OWNER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object newOwnerId_;
  /**
   * <code>string new_owner_id = 3;</code>
   */
  public java.lang.String getNewOwnerId() {
    java.lang.Object ref = newOwnerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newOwnerId_ = s;
      return s;
    }
  }
  /**
   * <code>string new_owner_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNewOwnerIdBytes() {
    java.lang.Object ref = newOwnerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newOwnerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNATURE_WAREHOUSE_CURRENT_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signatureWarehouseCurrent_;
  /**
   * <code>bytes signature_warehouse_current = 4;</code>
   */
  public com.google.protobuf.ByteString getSignatureWarehouseCurrent() {
    return signatureWarehouseCurrent_;
  }

  public static final int SIGNATURE_CURRENT_OWNER_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString signatureCurrentOwner_;
  /**
   * <code>bytes signature_current_owner = 5;</code>
   */
  public com.google.protobuf.ByteString getSignatureCurrentOwner() {
    return signatureCurrentOwner_;
  }

  public static final int SIGNATURE_WAREHOUSE_NEW_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString signatureWarehouseNew_;
  /**
   * <code>bytes signature_warehouse_new = 6;</code>
   */
  public com.google.protobuf.ByteString getSignatureWarehouseNew() {
    return signatureWarehouseNew_;
  }

  public static final int SIGNATURE_NEW_OWNER_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString signatureNewOwner_;
  /**
   * <code>bytes signature_new_owner = 7;</code>
   */
  public com.google.protobuf.ByteString getSignatureNewOwner() {
    return signatureNewOwner_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (receipt_ != null) {
      output.writeMessage(1, getReceipt());
    }
    if (!getCurrentOwnerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentOwnerId_);
    }
    if (!getNewOwnerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, newOwnerId_);
    }
    if (!signatureWarehouseCurrent_.isEmpty()) {
      output.writeBytes(4, signatureWarehouseCurrent_);
    }
    if (!signatureCurrentOwner_.isEmpty()) {
      output.writeBytes(5, signatureCurrentOwner_);
    }
    if (!signatureWarehouseNew_.isEmpty()) {
      output.writeBytes(6, signatureWarehouseNew_);
    }
    if (!signatureNewOwner_.isEmpty()) {
      output.writeBytes(7, signatureNewOwner_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (receipt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReceipt());
    }
    if (!getCurrentOwnerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentOwnerId_);
    }
    if (!getNewOwnerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, newOwnerId_);
    }
    if (!signatureWarehouseCurrent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, signatureWarehouseCurrent_);
    }
    if (!signatureCurrentOwner_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, signatureCurrentOwner_);
    }
    if (!signatureWarehouseNew_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, signatureWarehouseNew_);
    }
    if (!signatureNewOwner_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, signatureNewOwner_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.bverify.TransferReceiptRequest)) {
      return super.equals(obj);
    }
    io.grpc.bverify.TransferReceiptRequest other = (io.grpc.bverify.TransferReceiptRequest) obj;

    boolean result = true;
    result = result && (hasReceipt() == other.hasReceipt());
    if (hasReceipt()) {
      result = result && getReceipt()
          .equals(other.getReceipt());
    }
    result = result && getCurrentOwnerId()
        .equals(other.getCurrentOwnerId());
    result = result && getNewOwnerId()
        .equals(other.getNewOwnerId());
    result = result && getSignatureWarehouseCurrent()
        .equals(other.getSignatureWarehouseCurrent());
    result = result && getSignatureCurrentOwner()
        .equals(other.getSignatureCurrentOwner());
    result = result && getSignatureWarehouseNew()
        .equals(other.getSignatureWarehouseNew());
    result = result && getSignatureNewOwner()
        .equals(other.getSignatureNewOwner());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReceipt()) {
      hash = (37 * hash) + RECEIPT_FIELD_NUMBER;
      hash = (53 * hash) + getReceipt().hashCode();
    }
    hash = (37 * hash) + CURRENT_OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentOwnerId().hashCode();
    hash = (37 * hash) + NEW_OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNewOwnerId().hashCode();
    hash = (37 * hash) + SIGNATURE_WAREHOUSE_CURRENT_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureWarehouseCurrent().hashCode();
    hash = (37 * hash) + SIGNATURE_CURRENT_OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureCurrentOwner().hashCode();
    hash = (37 * hash) + SIGNATURE_WAREHOUSE_NEW_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureWarehouseNew().hashCode();
    hash = (37 * hash) + SIGNATURE_NEW_OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureNewOwner().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.bverify.TransferReceiptRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.bverify.TransferReceiptRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.TransferReceiptRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TransferReceiptRequest)
      io.grpc.bverify.TransferReceiptRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.bverify.Api.internal_static_api_TransferReceiptRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.bverify.Api.internal_static_api_TransferReceiptRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.bverify.TransferReceiptRequest.class, io.grpc.bverify.TransferReceiptRequest.Builder.class);
    }

    // Construct using io.grpc.bverify.TransferReceiptRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (receiptBuilder_ == null) {
        receipt_ = null;
      } else {
        receipt_ = null;
        receiptBuilder_ = null;
      }
      currentOwnerId_ = "";

      newOwnerId_ = "";

      signatureWarehouseCurrent_ = com.google.protobuf.ByteString.EMPTY;

      signatureCurrentOwner_ = com.google.protobuf.ByteString.EMPTY;

      signatureWarehouseNew_ = com.google.protobuf.ByteString.EMPTY;

      signatureNewOwner_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.bverify.Api.internal_static_api_TransferReceiptRequest_descriptor;
    }

    public io.grpc.bverify.TransferReceiptRequest getDefaultInstanceForType() {
      return io.grpc.bverify.TransferReceiptRequest.getDefaultInstance();
    }

    public io.grpc.bverify.TransferReceiptRequest build() {
      io.grpc.bverify.TransferReceiptRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.bverify.TransferReceiptRequest buildPartial() {
      io.grpc.bverify.TransferReceiptRequest result = new io.grpc.bverify.TransferReceiptRequest(this);
      if (receiptBuilder_ == null) {
        result.receipt_ = receipt_;
      } else {
        result.receipt_ = receiptBuilder_.build();
      }
      result.currentOwnerId_ = currentOwnerId_;
      result.newOwnerId_ = newOwnerId_;
      result.signatureWarehouseCurrent_ = signatureWarehouseCurrent_;
      result.signatureCurrentOwner_ = signatureCurrentOwner_;
      result.signatureWarehouseNew_ = signatureWarehouseNew_;
      result.signatureNewOwner_ = signatureNewOwner_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.bverify.TransferReceiptRequest) {
        return mergeFrom((io.grpc.bverify.TransferReceiptRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.bverify.TransferReceiptRequest other) {
      if (other == io.grpc.bverify.TransferReceiptRequest.getDefaultInstance()) return this;
      if (other.hasReceipt()) {
        mergeReceipt(other.getReceipt());
      }
      if (!other.getCurrentOwnerId().isEmpty()) {
        currentOwnerId_ = other.currentOwnerId_;
        onChanged();
      }
      if (!other.getNewOwnerId().isEmpty()) {
        newOwnerId_ = other.newOwnerId_;
        onChanged();
      }
      if (other.getSignatureWarehouseCurrent() != com.google.protobuf.ByteString.EMPTY) {
        setSignatureWarehouseCurrent(other.getSignatureWarehouseCurrent());
      }
      if (other.getSignatureCurrentOwner() != com.google.protobuf.ByteString.EMPTY) {
        setSignatureCurrentOwner(other.getSignatureCurrentOwner());
      }
      if (other.getSignatureWarehouseNew() != com.google.protobuf.ByteString.EMPTY) {
        setSignatureWarehouseNew(other.getSignatureWarehouseNew());
      }
      if (other.getSignatureNewOwner() != com.google.protobuf.ByteString.EMPTY) {
        setSignatureNewOwner(other.getSignatureNewOwner());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.bverify.TransferReceiptRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.bverify.TransferReceiptRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.grpc.bverify.Receipt receipt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder> receiptBuilder_;
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public boolean hasReceipt() {
      return receiptBuilder_ != null || receipt_ != null;
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public io.grpc.bverify.Receipt getReceipt() {
      if (receiptBuilder_ == null) {
        return receipt_ == null ? io.grpc.bverify.Receipt.getDefaultInstance() : receipt_;
      } else {
        return receiptBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public Builder setReceipt(io.grpc.bverify.Receipt value) {
      if (receiptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receipt_ = value;
        onChanged();
      } else {
        receiptBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public Builder setReceipt(
        io.grpc.bverify.Receipt.Builder builderForValue) {
      if (receiptBuilder_ == null) {
        receipt_ = builderForValue.build();
        onChanged();
      } else {
        receiptBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public Builder mergeReceipt(io.grpc.bverify.Receipt value) {
      if (receiptBuilder_ == null) {
        if (receipt_ != null) {
          receipt_ =
            io.grpc.bverify.Receipt.newBuilder(receipt_).mergeFrom(value).buildPartial();
        } else {
          receipt_ = value;
        }
        onChanged();
      } else {
        receiptBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public Builder clearReceipt() {
      if (receiptBuilder_ == null) {
        receipt_ = null;
        onChanged();
      } else {
        receipt_ = null;
        receiptBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public io.grpc.bverify.Receipt.Builder getReceiptBuilder() {
      
      onChanged();
      return getReceiptFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    public io.grpc.bverify.ReceiptOrBuilder getReceiptOrBuilder() {
      if (receiptBuilder_ != null) {
        return receiptBuilder_.getMessageOrBuilder();
      } else {
        return receipt_ == null ?
            io.grpc.bverify.Receipt.getDefaultInstance() : receipt_;
      }
    }
    /**
     * <code>.api.Receipt receipt = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder> 
        getReceiptFieldBuilder() {
      if (receiptBuilder_ == null) {
        receiptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.bverify.Receipt, io.grpc.bverify.Receipt.Builder, io.grpc.bverify.ReceiptOrBuilder>(
                getReceipt(),
                getParentForChildren(),
                isClean());
        receipt_ = null;
      }
      return receiptBuilder_;
    }

    private java.lang.Object currentOwnerId_ = "";
    /**
     * <code>string current_owner_id = 2;</code>
     */
    public java.lang.String getCurrentOwnerId() {
      java.lang.Object ref = currentOwnerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentOwnerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current_owner_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentOwnerIdBytes() {
      java.lang.Object ref = currentOwnerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentOwnerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current_owner_id = 2;</code>
     */
    public Builder setCurrentOwnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentOwnerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string current_owner_id = 2;</code>
     */
    public Builder clearCurrentOwnerId() {
      
      currentOwnerId_ = getDefaultInstance().getCurrentOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string current_owner_id = 2;</code>
     */
    public Builder setCurrentOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentOwnerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object newOwnerId_ = "";
    /**
     * <code>string new_owner_id = 3;</code>
     */
    public java.lang.String getNewOwnerId() {
      java.lang.Object ref = newOwnerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newOwnerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string new_owner_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNewOwnerIdBytes() {
      java.lang.Object ref = newOwnerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newOwnerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string new_owner_id = 3;</code>
     */
    public Builder setNewOwnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newOwnerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string new_owner_id = 3;</code>
     */
    public Builder clearNewOwnerId() {
      
      newOwnerId_ = getDefaultInstance().getNewOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string new_owner_id = 3;</code>
     */
    public Builder setNewOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newOwnerId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signatureWarehouseCurrent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature_warehouse_current = 4;</code>
     */
    public com.google.protobuf.ByteString getSignatureWarehouseCurrent() {
      return signatureWarehouseCurrent_;
    }
    /**
     * <code>bytes signature_warehouse_current = 4;</code>
     */
    public Builder setSignatureWarehouseCurrent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureWarehouseCurrent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature_warehouse_current = 4;</code>
     */
    public Builder clearSignatureWarehouseCurrent() {
      
      signatureWarehouseCurrent_ = getDefaultInstance().getSignatureWarehouseCurrent();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signatureCurrentOwner_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature_current_owner = 5;</code>
     */
    public com.google.protobuf.ByteString getSignatureCurrentOwner() {
      return signatureCurrentOwner_;
    }
    /**
     * <code>bytes signature_current_owner = 5;</code>
     */
    public Builder setSignatureCurrentOwner(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureCurrentOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature_current_owner = 5;</code>
     */
    public Builder clearSignatureCurrentOwner() {
      
      signatureCurrentOwner_ = getDefaultInstance().getSignatureCurrentOwner();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signatureWarehouseNew_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature_warehouse_new = 6;</code>
     */
    public com.google.protobuf.ByteString getSignatureWarehouseNew() {
      return signatureWarehouseNew_;
    }
    /**
     * <code>bytes signature_warehouse_new = 6;</code>
     */
    public Builder setSignatureWarehouseNew(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureWarehouseNew_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature_warehouse_new = 6;</code>
     */
    public Builder clearSignatureWarehouseNew() {
      
      signatureWarehouseNew_ = getDefaultInstance().getSignatureWarehouseNew();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signatureNewOwner_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature_new_owner = 7;</code>
     */
    public com.google.protobuf.ByteString getSignatureNewOwner() {
      return signatureNewOwner_;
    }
    /**
     * <code>bytes signature_new_owner = 7;</code>
     */
    public Builder setSignatureNewOwner(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureNewOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature_new_owner = 7;</code>
     */
    public Builder clearSignatureNewOwner() {
      
      signatureNewOwner_ = getDefaultInstance().getSignatureNewOwner();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.TransferReceiptRequest)
  }

  // @@protoc_insertion_point(class_scope:api.TransferReceiptRequest)
  private static final io.grpc.bverify.TransferReceiptRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.bverify.TransferReceiptRequest();
  }

  public static io.grpc.bverify.TransferReceiptRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransferReceiptRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransferReceiptRequest>() {
    public TransferReceiptRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransferReceiptRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransferReceiptRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransferReceiptRequest> getParserForType() {
    return PARSER;
  }

  public io.grpc.bverify.TransferReceiptRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

