// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface TransferReceiptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TransferReceiptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  boolean hasReceipt();
  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  io.grpc.bverify.Receipt getReceipt();
  /**
   * <code>.api.Receipt receipt = 1;</code>
   */
  io.grpc.bverify.ReceiptOrBuilder getReceiptOrBuilder();

  /**
   * <code>string current_owner_id = 2;</code>
   */
  java.lang.String getCurrentOwnerId();
  /**
   * <code>string current_owner_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentOwnerIdBytes();

  /**
   * <code>string new_owner_id = 3;</code>
   */
  java.lang.String getNewOwnerId();
  /**
   * <code>string new_owner_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewOwnerIdBytes();

  /**
   * <code>bytes signature_warehouse_current = 4;</code>
   */
  com.google.protobuf.ByteString getSignatureWarehouseCurrent();

  /**
   * <code>bytes signature_current_owner = 5;</code>
   */
  com.google.protobuf.ByteString getSignatureCurrentOwner();

  /**
   * <code>bytes signature_warehouse_new = 6;</code>
   */
  com.google.protobuf.ByteString getSignatureWarehouseNew();

  /**
   * <code>bytes signature_new_owner = 7;</code>
   */
  com.google.protobuf.ByteString getSignatureNewOwner();
}
